### ISSUE TITLE
Plugin crash: Attempted to intern `'_#0r` which contains inference types/regions in the global type context

### ISSUE THREAD

**Issue by JDemler** [Manishearth/rust-clippy#1341]
`cargo +nightly clippy` is crashing when I run it against my project:

```
Compiling perlin v0.1.0 (file:///home/jdemler/Documents/programmieren/rust/perlin)
error: internal compiler error: ../src/librustc/ty/context.rs:1218: Attempted to intern `'_#0r` which contains inference types/regions in the global type context

thread 'main' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:424
```
Executed after running `rustup update` and `cargo uninstall clippy && cargo +nightly install clippy`.

Alas, I don't really know where to begin to look for the bug. So providing a minimal example proves to be quite difficult for me.
Nevertheless, I will be standing by to answer questinons and help wherever I can.

How to reproduce:

```
git clone -b fb-lazy_decoding https://github.com/JDemler/perlin.git
cd perlin/
cargo +nightly clippy
```

Complete Backtrace: 
```
stack backtrace:
   1:     0x7f54db72f7fa - std::sys::imp::backtrace::tracing::imp::write::he3d1bfbdbf113480
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f54db74199f - std::panicking::default_hook::{{closure}}::h575f1b40d2e88f07
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x7f54db73e256 - std::panicking::default_hook::h3d5dccce8125d0cf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x7f54db73e907 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x7f54dbbfa36a - std::panicking::begin_panic::hc24c3350b244bd01
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x7f54dbc0b5dd - rustc_errors::Handler::bug::h96bc36de2fd6ebdd
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_errors/lib.rs:424
   7:     0x7f54dca03af1 - rustc::session::opt_span_bug_fmt::{{closure}}::h1b6c9862d0821845
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/session/mod.rs:770
   8:     0x7f54dc93afce - rustc::session::opt_span_bug_fmt::haa780af58a54c675
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/context.rs:995
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/session/mod.rs:766
   9:     0x7f54dc93ac32 - rustc::session::bug_fmt::h6415832f75d41b15
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/session/mod.rs:750
  10:     0x7f54dc9f49c3 - rustc::ty::context::TyCtxt::mk_region::h71f1b3512f91ca2e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/context.rs:1218
  11:     0x7f54dc99623a - rustc::ty::subst::<impl rustc::ty::Slice<rustc::ty::subst::Kind<'tcx>>>::fill_item::he2ca0244a6c35538
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/infer/mod.rs:1211
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/infer/mod.rs:1220
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/infer/mod.rs:1259
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/subst.rs:209
  12:     0x7f54dc8b4ee8 - rustc::infer::InferCtxt::fresh_substs_for_item::h13cbb1073bde8f30
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/subst.rs:182
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/infer/mod.rs:1258
  13:     0x7f54dc968037 - rustc::traits::select::SelectionContext::match_impl::h8a4b0cbb23927421
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/select.rs:2689
  14:     0x7f54dca04815 - rustc::traits::select::SelectionContext::confirm_impl_candidate::{{closure}}::h307b7e9f57dbbd2d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/select.rs:2658
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/select.rs:2244
  15:     0x7f54dc8b20b0 - rustc::infer::InferCtxt::in_snapshot::h91f516535d753464
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/select.rs:358
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/infer/mod.rs:984
  16:     0x7f54dc962642 - rustc::traits::select::SelectionContext::confirm_candidate::h196c936a42d38d3e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/select.rs:358
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/select.rs:2242
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/select.rs:2023
  17:     0x7f54dc9595c1 - rustc::traits::select::SelectionContext::select::h67535d119c5a2022
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/select.rs:420
  18:     0x7f54dca016cf - rustc::traits::project::assemble_candidates_from_impls::{{closure}}::hd4d77a221525dd0b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/project.rs:885
  19:     0x7f54dc954c9d - rustc::traits::project::assemble_candidates_from_impls::h62082143d0f65dda
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/infer/mod.rs:1038
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/project.rs:884
  20:     0x7f54dc95332c - rustc::traits::project::opt_normalize_projection_type::hff897802964b31ba
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/project.rs:686
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/project.rs:499
  21:     0x7f54dc951d9d - rustc::traits::project::normalize_projection_type::h8634ccd683516b32
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/project.rs:384
  22:     0x7f54dc95197f - <rustc::traits::project::AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty::h39e5277662362fe4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/project.rs:339
  23:     0x7f54dc94fe0b - rustc::traits::project::normalize_with_depth::h3b91e309ae569770
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/structural_impls.rs:491
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/project.rs:289
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/project.rs:251
  24:     0x7f54dc9861aa - rustc::ty::layout::normalize_associated_type::h9b46d9022ddc23a1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/traits/project.rs:236
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/layout.rs:861
  25:     0x7f54dc98659f - rustc::ty::layout::Layout::compute_uncached::hadda631efd88c8ac
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/layout.rs:1188
  26:     0x7f54dc9a13b3 - rustc::ty::util::<impl rustc::ty::TyS<'tcx>>::layout::h2aecdc4ab0b6b483
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/util.rs:716
  27:     0x7f54dc987f86 - rustc::ty::layout::Layout::compute_uncached::hadda631efd88c8ac
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/layout.rs:1065
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/ops.rs:2645
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/option.rs:383
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/iter/mod.rs:982
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/layout.rs:583
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/layout.rs:1067
  28:     0x7f54dc9a13b3 - rustc::ty::util::<impl rustc::ty::TyS<'tcx>>::layout::h2aecdc4ab0b6b483
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/util.rs:716
  29:     0x7f54dc986967 - rustc::ty::layout::Layout::compute_uncached::hadda631efd88c8ac
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/layout.rs:1030
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/ops.rs:2645
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/option.rs:383
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/iter/mod.rs:982
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/layout.rs:542
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/layout.rs:1039
  30:     0x55f90ff74c76 - clippy_lints::escape::EscapeDelegate::is_large_box::h7c9f918edac70ebc
  31:     0x55f90ff74293 - <clippy_lints::escape::EscapeDelegate<'a, 'tcx, 'gcx> as rustc::middle::expr_use_visitor::Delegate<'tcx>>::consume_pat::h79966821d969dd8e
  32:     0x7f54dc8fcc12 - rustc::middle::mem_categorization::MemCategorizationContext::cat_pattern_::h4ce721df162d25c7
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/middle/expr_use_visitor.rs:969
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/middle/mem_categorization.rs:1065
  33:     0x7f54dc8dfaba - rustc::middle::expr_use_visitor::ExprUseVisitor::walk_pat::hb1a151336f1afe57
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/middle/mem_categorization.rs:1011
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/middle/expr_use_visitor.rs:969
  34:     0x7f54dc8dfa0f - rustc::middle::expr_use_visitor::ExprUseVisitor::walk_irrefutable_pat::h1c41a3fa79c3ce89
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/middle/expr_use_visitor.rs:932
  35:     0x7f54dc8dd71e - rustc::middle::expr_use_visitor::ExprUseVisitor::walk_fn::hba7707969ad7d709
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/middle/expr_use_visitor.rs:311
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/middle/expr_use_visitor.rs:294
  36:     0x55f90ff739db - <clippy_lints::escape::Pass as rustc::lint::LateLintPass>::check_fn::hb5e7f8269426b190
  37:     0x7f54dc8d2f81 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_fn::hacc676050a737fe1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:842
  38:     0x7f54dc833978 - rustc::hir::intravisit::walk_impl_item::hcf99636e58a2a4e8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/hir/intravisit.rs:690
  39:     0x7f54dc8cc78d - rustc::lint::context::LintContext::with_lint_attrs::he4bd327352985e7e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:933
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:679
  40:     0x7f54dc8d208a - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_item::h4a56c5141518ee13
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:930
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/hir/intravisit.rs:349
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:805
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:679
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:802
  41:     0x7f54dc8d3fbb - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_mod::ha9768ff6f49f3ae0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:798
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/hir/intravisit.rs:240
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:884
  42:     0x7f54dc8d1d31 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_item::h4a56c5141518ee13
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/hir/intravisit.rs:324
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:805
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:679
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:802
  43:     0x7f54dc8d3fbb - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_mod::ha9768ff6f49f3ae0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:798
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/hir/intravisit.rs:240
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:884
  44:     0x7f54dc8d1d31 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_item::h4a56c5141518ee13
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/hir/intravisit.rs:324
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:805
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:679
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:802
  45:     0x7f54dc8d3fbb - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_mod::ha9768ff6f49f3ae0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:798
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/hir/intravisit.rs:240
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:884
  46:     0x7f54dc8d1d31 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_item::h4a56c5141518ee13
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/hir/intravisit.rs:324
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:805
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:679
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:802
  47:     0x7f54dc8d3fbb - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_mod::ha9768ff6f49f3ae0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:798
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/hir/intravisit.rs:240
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:884
  48:     0x7f54dc8da370 - rustc::lint::context::check_crate::h36077ff1011a9573
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/hir/intravisit.rs:225
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:1258
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:679
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/lint/context.rs:1249
  49:     0x7f54dd201a9d - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::hb062c53ab7b33bac
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/driver.rs:972
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/util/common.rs:38
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/driver.rs:970
  50:     0x7f54dd1cccb0 - rustc_driver::driver::phase_3_run_analysis_passes::h016090d638ff1d7f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/context.rs:966
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:245
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/context.rs:963
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/context.rs:950
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:245
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/context.rs:947
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc/ty/context.rs:735
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/driver.rs:854
  51:     0x7f54dd1bf504 - rustc_driver::driver::compile_input::h21840cdf516c3ab1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/driver.rs:172
  52:     0x7f54dd1e96a0 - rustc_driver::run_compiler::h81a62653df4e7b03
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/librustc_driver/lib.rs:222
  53:     0x55f90feefef0 - cargo_clippy::main::h56dcb6fe35f2e411
  54:     0x7f54db7498aa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  55:     0x7f54db73f7f5 - std::rt::lang_start::h74b3afbdd8daef1c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  56:     0x7f54dac05290 - __libc_start_main
  57:     0x55f90fee5db9 - _start
  58:                0x0 - <unknown>
```

**Comment by mcarton** [comment]
Reduced test case:

```rust
pub trait Foo {
    type Item;
}

impl<'a> Foo for &'a () {
    type Item = ();
}

pub struct PeekableSeekable<I: Foo> {
    peeked: I::Item,
}

pub fn new<'a>(needs_name: Box<PeekableSeekable<&'a ()>>) -> () {
    unimplemented!()
}
```
