### ISSUE TITLE
clippy build fails on rustc 1.19.0-nightly (5b13bff52 2017-05-23)

### ISSUE THREAD

**Issue by imiuka** [Manishearth/rust-clippy#1778]
hello,

clippy no longer builds on today's nightly:
```
rustc 1.19.0-nightly (5b13bff52 2017-05-23)
binary: rustc
commit-hash: 5b13bff5203c1bdc6ac6dc87f69b5359a9503078
commit-date: 2017-05-23
host: x86_64-pc-windows-msvc
release: 1.19.0-nightly
LLVM version: 4.0

-------

error: no method named `parameter_environment` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> /home/hina/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.134/src/utils/mod.rs:790:32
    |
790 |     let parameter_env = cx.tcx.parameter_environment(parameter_item);
    |                                ^^^^^^^^^^^^^^^^^^^^^

error: no method named `parameter_environment` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
   --> /home/hina/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.134/src/utils/mod.rs:810:22
    |
810 |     let env = cx.tcx.parameter_environment(env);
    |                      ^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> /home/hina/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.134/src/utils/mod.rs:811:69
    |
811 |     !ty.subst(cx.tcx, substs).moves_by_default(cx.tcx.global_tcx(), &env, DUMMY_SP)
    |                                                                     ^^^^ expected struct `rustc::ty::ParamEnv`, found reference
    |
    = note: expected type `rustc::ty::ParamEnv<'_>`
               found type `&_`

error: no method named `parameter_environment` found for type `rustc::ty::TyCtxt<'a, 'tcx, 'tcx>` in the current scope
  --> /home/hina/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.134/src/needless_pass_by_value.rs:85:40
   |
85 |             let parameter_env = cx.tcx.parameter_environment(fn_def_id);
   |                                        ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

error: Could not compile `clippy_lints`.
Build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.134`, intermediate artifacts can be found at `/tmp/cargo-install.Aj3xdnFKxl2g`

Caused by:
  build failed
```

**Comment by oli-obk** [comment]
fixed in e72c70d077bb0a1a8eedb563545a142c7d5e2ab3 but publishing (only of clippy, not of clippy_lints) fails with 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAfterTable', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: cargo::core::package::Package::to_registry_toml
  11: cargo::ops::cargo_package::package
  12: cargo::ops::registry::publish
  13: cargo::try_execute_builtin_command
  14: cargo::execute
  15: cargo::call_main_without_stdin
  16: cargo::main
  17: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  18: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:56
  19: __libc_start_main
  20: <unknown>
```

compiling works fine :/

**Comment by oli-obk** [comment]
please use a git dependency or install from git for now while we figure this out

**Comment by ForsakenHarmony** [comment]
I'm having problems with this

```
$ cargo build --features clippy
   Compiling clippy_lints v0.0.135 (https://github.com/Manishearth/rust-clippy#e72c70d0)
error[E0422]: cannot find struct, variant or union type `Substitution` in module `rustc_errors`
   --> ~\.cargo\git\checkouts\rust-clippy-eb94f5e90699ab2d\e72c70d\clippy_lints\src\utils\mod.rs:595:78
    |
595 |         substitution_parts: sugg.into_iter().map(|(span, sub)| rustc_errors::Substitution { span, substitutions: vec![sub] }).collect(),
    |                                                                              ^^^^^^^^^^^^ not found in `rustc_errors`

error[E0106]: missing lifetime specifier
   --> ~\.cargo\git\checkouts\rust-clippy-eb94f5e90699ab2d\e72c70d\clippy_lints\src\loops.rs:876:35
    |
876 |     indexed: HashMap<Name, Option<CodeExtent>>, // indexed variables, the extent is None for global
    |                                   ^^^^^^^^^^ expected lifetime parameter

error: aborting due to previous error

error: Could not compile `clippy_lints`.

To learn more, run the command again with --verbose.
```

**Comment by jbg** [comment]
I've been getting that error running `cargo publish` intermittently too. I just retry a few times and it works eventually.

**Comment by oli-obk** [comment]
The code extend error means your checkout is outdated. You need the latest master branch

I'll try repeating a few more times,

**Comment by Manishearth** [comment]
Fix was published, clippy publishes again and works now.

**Comment by ForsakenHarmony** [comment]
@oli-obk I'm on the latest master branch, still the same error
