### ISSUE TITLE
ICE in `CYCLOMATIC_COMPLEXITY` lint

### ISSUE THREAD

**Issue by mcarton** [Manishearth/rust-clippy#759]
This is a corner case but:
```rust
#![feature(plugin)]
#![plugin(clippy)]

fn main() {
    panic!("foo");
    panic!("bar");
}
```
produces
```
thread 'rustc' panicked at 'arithmetic operation overflowed', src/cyclomatic_complexity.rs:50
stack backtrace:
   1:     0x7efe090c5c00 - sys::backtrace::tracing::imp::write::h752705b18648d1caEIv
   2:     0x7efe090cfd4f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.45061
   3:     0x7efe090cf8c3 - panicking::default_handler::hd7da873c55525eaaRxA
   4:     0x7efe090958ec - sys_common::unwind::begin_unwind_inner::h9832d329b70049c9Xwu
   5:     0x7efe09096388 - sys_common::unwind::begin_unwind_fmt::h7902ea6e35d437ab3vu
   6:     0x7efe090c34f1 - rust_begin_unwind
   7:     0x7efe0911972f - panicking::panic_fmt::h8917bddd72ecec2e7mM
   8:     0x7efe0911a228 - panicking::panic::hfdb00a67c0f7ae10ElM
   9:     0x7efdfce56696 - cyclomatic_complexity::CyclomaticComplexity::check::hc0f30a0b60aaa641IKd
                        at src/cyclomatic_complexity.rs:50
  10:     0x7efdfcdbd82b - cyclomatic_complexity::CyclomaticComplexity.LateLintPass::check_item::he996ea6d943fc232kNd
                        at src/cyclomatic_complexity.rs:83
  11:     0x7efe06564f74 - lint::context::LateContext<'a, 'tcx>.hir_visit..Visitor<'v>::visit_item::hd1b9d7e01c5f227783u
  12:     0x7efe0656a77b - lint::context::LateContext<'a, 'tcx>.hir_visit..Visitor<'v>::visit_mod::hf7e163939be2ca2dAgv
  13:     0x7efe0658c8ea - lint::context::check_crate::ha3f43facd529952ae6v
  14:     0x7efe09607910 - driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::closure.30211
  15:     0x7efe09602014 - middle::ty::context::TyCtxt<'tcx>::create_and_enter::h17882283280588378896
  16:     0x7efe095febf2 - driver::phase_3_run_analysis_passes::h13919317650711339916
  17:     0x7efe095d13bf - driver::compile_input::h148bbe225adb9061Pca
  18:     0x7efe095beb46 - run_compiler::h01319ef2912a48felQc
  19:     0x7efe095bc2c1 - sys_common::unwind::try::try_fn::h15450783821430179622
  20:     0x7efe090c347b - __rust_try
  21:     0x7efe090c340d - sys_common::unwind::inner_try::hfb91b5cfe185b795Ztu
  22:     0x7efe095bcb0a - boxed::F.FnBox<A>::call_box::h7115862480082857486
  23:     0x7efe090cde59 - sys::thread::Thread::new::thread_start::h33a79b9c7e674b88Huz
  24:     0x7efe01842423 - start_thread
  25:     0x7efe08d44cbc - clone
  26:                0x0 - <unknown>
```

Cc @oli-obk.

**Comment by oli-obk** [comment]
Wrong backtrace?

Curious case. Maybe it's happening in the control flow graph generation. This would be a bug in rustc

**Comment by mcarton** [comment]
> Wrong backtrace?

Oh yeah, edited :smile:.

> Curious case. Maybe it's happening in the control flow graph generation. This would be a bug in rustc

Nope, looks like [`e + 2 < n`](https://github.com/Manishearth/rust-clippy
/blob/eba41430ce04ef64689acd1b991610076a3305db/src/cyclomatic_complexity.rs#L50).
