### ISSUE TITLE
`cargo clippy` panics with 'could not obtain cargo metadata'

### ISSUE THREAD

**Issue by euclio** [Manishearth/rust-clippy#973]
I am trying to run `cargo clippy` 0.0.71 on the Hoverbear/rust-rosetta repository.

I installed `cargo clippy` with `rustup run nightly cargo install clippy`.

The repository has a toolchain override pointing to the latest nightly.

```
$ rustc --version
rustc 1.11.0-nightly (601eb13dc 2016-05-31)
$ env RUST_BACKTRACE=1 cargo clippy
thread '<main>' panicked at 'could not obtain cargo metadata: Json(ExpectedError("Object", "\"pattern\""))', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x7f2a8b34b3e4 - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x7f2a8b3599ab - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x7f2a8b3595e3 - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x7f2a8b31c92d - std::panicking::rust_panic_with_hook::h587239a80cad02d2
   5:     0x7f2a8b359c41 - std::panicking::begin_panic::h77cefecf7d758cdf
   6:     0x7f2a8b31ea7a - std::panicking::begin_panic_fmt::hb3024643f3039337
   7:     0x7f2a8b359bd1 - rust_begin_unwind
   8:     0x7f2a8b3a309f - core::panicking::panic_fmt::h5594591d20dedfcd
   9:     0x55c0355a37ae - core::result::unwrap_failed::h5961dc49f071615e
  10:     0x55c0355a224c - cargo_clippy::main::hd4e6cdc692d85a27
  11:     0x7f2a8b359088 - std::panicking::try::call::hd0906b54b9bfbb20
  12:     0x7f2a8b36832b - __rust_try
  13:     0x7f2a8b3682ce - __rust_maybe_catch_panic
  14:     0x7f2a8b358abc - std::rt::lang_start::hfe4efe1fc39e4a30
  15:     0x7f2a8a7a6740 - __libc_start_main
  16:     0x55c035598838 - _start
  17:                0x0 - <unknown>
error: 

```

Please let me know if I can provide more information. This crate is an interesting case because it has a large number of binaries that do not share a main library.

**Comment by oli-obk** [comment]
hmm... can you include the output of `cargo metadata --no-deps`? I probably forgot something in the datastructure that we use to parse the json.

**Comment by mmstick** [comment]
Getting the same problem myself.

```
thread '<main>' panicked at 'could not obtain cargo metadata: Json(UnknownVariantError("example"))', ../src/libcore/result.rs:785
```
```
{"packages":[{"name":"flac","version":"0.4.0","id":"flac 0.4.0 (path+file:///home/mmstick/Programming/flac)","source":null,"dependencies":[{"name":"rustc-serialize","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.3.16","kind":null,"optional":false,"uses_default_features":true,"features":[],"target":null},{"name":"docopt","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.6.78","kind":null,"optional":false,"uses_default_features":true,"features":[],"target":null},{"name":"hound","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.1.0","kind":null,"optional":false,"uses_default_features":true,"features":[],"target":null},{"name":"nom","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^1.0.0","kind":null,"optional":false,"uses_default_features":true,"features":[],"target":null},{"name":"rust-crypto","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.2.34","kind":"dev","optional":false,"uses_default_features":true,"features":[],"target":null}],"targets":[{"kind":["lib"],"name":"flac","src_path":"/home/mmstick/Programming/flac/src/lib.rs"},{"kind":["example"],"name":"decode","src_path":"/home/mmstick/Programming/flac/examples/decode.rs"},{"kind":["example"],"name":"metadata","src_path":"/home/mmstick/Programming/flac/examples/metadata.rs"},{"kind":["test"],"name":"metadata","src_path":"/home/mmstick/Programming/flac/tests/metadata.rs"},{"kind":["test"],"name":"stream","src_path":"/home/mmstick/Programming/flac/tests/stream.rs"}],"features":{},"manifest_path":"/home/mmstick/Programming/flac/Cargo.toml"}],"resolve":null,"version":1}
```

**Comment by oli-obk** [comment]
that's actually a distinct one :(

**Comment by mmstick** [comment]
Also getting this one with one of my projects:

```
thread '<main>' panicked at 'could not obtain cargo metadata: Json(ExpectedError("Object", "\"v3_16\""))', ../src/libcore/result.rs:785
```

```
{"packages":[{"name":"systemd-manager","version":"0.4.6","id":"systemd-manager 0.4.6 (path+file:///home/mmstick/Programming/systemd-manager)","source":null,"dependencies":[{"name":"gdk","source":"git+https://github.com/gtk-rs/gdk.git","req":"*","kind":null,"optional":false,"uses_default_features":true,"features":[],"target":null},{"name":"dbus","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^0.3.3","kind":null,"optional":false,"uses_default_features":true,"features":[],"target":null},{"name":"quickersort","source":"registry+https://github.com/rust-lang/crates.io-index","req":"^2.0.1","kind":null,"optional":false,"uses_default_features":true,"features":[],"target":null},{"name":"gtk","source":"git+https://github.com/gtk-rs/gtk.git","req":"*","kind":null,"optional":false,"uses_default_features":true,"features":["v3_16"],"target":null}],"targets":[{"kind":["bin"],"name":"systemd-manager","src_path":"/home/mmstick/Programming/systemd-manager/src/main.rs"}],"features":{},"manifest_path":"/home/mmstick/Programming/systemd-manager/Cargo.toml"}],"resolve":null,"version":1}
```

**Comment by llogiq** [comment]
Reopen because #974 only partially fixed this.

**Comment by euclio** [comment]
Indeed, now I'm getting

```
$ env RUST_BACKTRACE=1 cargo clippy
thread '<main>' panicked at 'could not obtain cargo metadata: Json(ExpectedError("Null", "\"cfg(windows)\""))', ../src/libcore/result.rs:785
stack backtrace:
   1:        0x10a3c4065 - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:        0x10a3d0e2a - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:        0x10a3d0a0a - std::panicking::default_hook::he0146e6a74621cb4
   4:        0x10a394437 - std::panicking::rust_panic_with_hook::h587239a80cad02d2
   5:        0x10a3d1446 - std::panicking::begin_panic::h77cefecf7d758cdf
   6:        0x10a396428 - std::panicking::begin_panic_fmt::hb3024643f3039337
   7:        0x10a3d1097 - rust_begin_unwind
   8:        0x10a40d110 - core::panicking::panic_fmt::h5594591d20dedfcd
   9:        0x10549ca3b - core::result::unwrap_failed::he99009635ff5bb81
  10:        0x10549b32a - cargo_clippy::main::hd4e6cdc692d85a27
  11:        0x10a3d035d - std::panicking::try::call::hd0906b54b9bfbb20
  12:        0x10a3d823b - __rust_try
  13:        0x10a3d81d5 - __rust_maybe_catch_panic
  14:        0x10a3d0161 - std::rt::lang_start::hfe4efe1fc39e4a30
error:
```

**Comment by llogiq** [comment]
@euclio Can you please update clippy and re-check?

**Comment by euclio** [comment]
@llogiq Seems to be working. Thanks all!

**Comment by llogiq** [comment]
Thanks @euclio
